generate/urls.py
from django.urls import path,include
from . import views

app_name = 'generate'
urlpatterns = [
    path('',views.home,name='gen'),
    path('record',views.record,name='record'),
    path('trans',views.translation,name='translate'),
    path('textgen',views.text_gen,name='text_gen'),
    #path('home_1',views.home_1,name='home_1'),
    path('record_1',views.record_1,name='record_1'),
    path('final',views.final,name='final'),
    path('sentimental',views.sentimental,name='sentimental'),
    
]

speech_assist/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('generate/',include('generate.urls'))
]

generate/models.py
from django.db import models

# Create your models here.

generate/views.py
from django.shortcuts import render
from textblob import TextBlob
import speech_recognition as sr
# import langdetect.detector
from langdetect import detect
from django.http import HttpResponse

from googletrans import Translator
import googletrans


import tensorflow as tf
import pandas as pd
import numpy as np
import re                               
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.layers import Input, Dense, Embedding, LSTM, Dropout, Bidirectional, GlobalMaxPooling1D
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential


from keras.models import load_model

import re                                

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

from tensorflow.keras.utils import to_categorical

import os
from google.cloud import translate_v2 as translate

os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = r"E:\7th_sem\NLP\Project_working_area\django_implementation\text-generate-main\generate\hip-heading-283511-c145f68ba57b.json"
#from googletrans import Translator
#import googletrans
######### sentimental
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import spacy 
nlp = spacy.load('en_core_web_sm', parse=True, tag=True, entity=True)
import nltk
from nltk.tokenize.toktok import ToktokTokenizer
import re
tokenizer = ToktokTokenizer()
stopword_list = nltk.corpus.stopwords.words('english')
stopword_list.remove('no')
stopword_list.remove('not')
import unicodedata
from better_profanity import profanity
from textblob import TextBlob

tokenizer = ToktokTokenizer()


#############
def text_translate(txt,lang):
    k=googletrans.LANGUAGES
    lng2 = lang
    for key, value in k.items():
        if lng2 == value:
            y=key



    translate_client = translate.Client()

    text = txt
    target = y

    output = translate_client.translate(
        text,
        target_language=target
    )

    return (output['translatedText'])



# Create your views here.
def home(request):
    return render(request,'generate/home.html')

def speech():
    # import speech_recognition as sr       ### Using HMM model as API
    # from langdetect import detect  
    # from textblob import TextBlob

    r1 = sr.Recognizer()
    with sr.Microphone() as source:
        print("Say something...")
        audio_data = r1.listen(source, timeout=7)
        print("Recognizing...")
        try:
            #text = r.recognize_google(audio_data)# api's::--  recognize_bing(): Microsoft Bing Speech , recognize_google_cloud(): Google Cloud Speech , 
            li = []                                         #recognize_ibm(): IBM Speech to Text
            x = (r1.recognize_google(audio_data))
            print(x)
            z = (TextBlob(x))
            lang = (z.detect_language())
            x = (r1.recognize_google(audio_data, language=lang))
            li.append(x)
            y = detect(x)
            li.append(y)
            return li
            #print(text)
        except:
            #print("Sorry, please try again...")
            return 0


# def text_translate(inp,ln):
#     # from googletrans import Translator
#     # import googletrans
#     k=googletrans.LANGUAGES
#     if len(inp) == 2:
#       lng1 = inp[1]
#     else:
#       lng1 = ln
    
#     for key, value in k.items():
#         if lng1 == key:
#             x=key
#     lng2 = 'english'
#     for key, value in k.items():
#         if lng2 == value:
#             y=key
#     if len(inp) == 2:
#       text1=inp[0]
#     else:
#       text1 = inp
#     translator = Translator()
#     translated = translator.translate(text1, src=x, dest=y)
#     #print("The translated text in",lng2,"is : ",translated.text.lower())
#     return ((translated.text)).lower()

# def text_translate_1(inp,ln):
#     # from googletrans import Translator
#     # import googletrans

#     k=googletrans.LANGUAGES
#     lng1 = inp[1]
#     for key, value in k.items():
#         if lng1 == key:
#             x=key
#     lng2 = ln
#     for key, value in k.items():
#         if lng2 == value:
#             y=key
#     text1=inp[0]
#     translator = Translator()
#     translated = translator.translate(text1, src=x, dest=y)
#     #print("The translated text in",lng2,"is : ",translated.text.lower())
#     return ((translated.text)).lower()
# def text_translate_2(inp,ln):
#     # from googletrans import Translator
#     # import googletrans

#     k=googletrans.LANGUAGES
#     lng1 = inp[1]
#     for key, value in k.items():
#         if lng1 == key:
#             x=key
#     lng2 = ln
#     for key, value in k.items():
#         if lng2 == value:
#             y=key
#     text1=inp[0]
#     translator = Translator()
#     translated = translator.translate(text1, src=x, dest=y)
#     #print("The translated text in",lng2,"is : ",translated.text.lower())
#     return ((translated.text)).lower()
# def text_translate_3(inp,ln):
#     # from googletrans import Translator
#     # import googletrans

#     k=googletrans.LANGUAGES
#     lng1 = inp[1]
#     for key, value in k.items():
#         if lng1 == key:
#             x=key
#     lng2 = ln
#     for key, value in k.items():
#         if lng2 == value:
#             y=key
#     text1=inp[0]
#     translator = Translator()
#     translated = translator.translate(text1, src=x, dest=y)
#     #print("The translated text in",lng2,"is : ",translated.text.lower())
#     return ((translated.text)).lower()


def sub_text_generation(txt,data_set,hd5_file):
  # import tensorflow as tf
  # import pandas as pd
  # import numpy as np
  # import re                               
  # from tensorflow.keras.preprocessing.text import Tokenizer
  # from tensorflow.keras.preprocessing.sequence import pad_sequences
  # from tensorflow.keras.utils import to_categorical
  # from tensorflow.keras.layers import Input, Dense, Embedding, LSTM, Dropout, Bidirectional, GlobalMaxPooling1D
  # from tensorflow.keras.models import Model
  # from tensorflow.keras.optimizers import Adam
  # from tensorflow.keras.models import Sequential


  # from keras.models import load_model

  with open(data_set, encoding="utf8") as story:
      story_data = story.read()

  # import re                                

  def clean_text(text):
      text = re.sub(r',', '', text)
      text = re.sub(r'\'', '',  text)
      text = re.sub(r'\"', '', text)
      text = re.sub(r'\(', '', text)
      text = re.sub(r'\)', '', text)
      text = re.sub(r'\n', '', text)
      text = re.sub(r'“', '', text)
      text = re.sub(r'”', '', text)
      text = re.sub(r'’', '', text)
      text = re.sub(r'\.', '', text)
      text = re.sub(r';', '', text)
      text = re.sub(r':', '', text)
      text = re.sub(r'\-', '', text)

      return text

  # cleaning the data
  lower_data = story_data.lower()           

  split_data = lower_data.splitlines()      

  final = ''                                

  for line in split_data:
      line = clean_text(line)
      final += '\n' + line

  #print(final)

  final_data = final.split('\n')       
  #print(final_data)

  # from tensorflow.keras.preprocessing.text import Tokenizer
  # from tensorflow.keras.preprocessing.sequence import pad_sequences

  # Instantiating the Tokenizer
  max_vocab = 1000000
  tokenizer = Tokenizer(num_words=max_vocab)
  tokenizer.fit_on_texts(final_data)

  # Getting the total number of words of the data.
  word2idx = tokenizer.word_index
  #print(len(word2idx))
  #print(word2idx)
  vocab_size = len(word2idx) + 1       
  #print(vocab_size)
  #n-grams
  #The sentence ['my name is shiva ji and happy'] will have sequence as [112, 113, 114, 7, 5, 190, 75]
  # * [112, 113], 
  # * [112, 113, 114], 
  # * [112, 113, 114, 7], 
  # * [112, 113, 114, 7, 5], 
  # * [112, 113, 114, 7, 5, 190],
  # * [112, 113, 114, 7, 5, 190, 75], 

  input_seq = []

  for line in final_data:
      token_list = tokenizer.texts_to_sequences([line])[0]
      for i in range(1, len(token_list)):
          n_gram_seq = token_list[:i+1]
          input_seq.append(n_gram_seq)

  #print(input_seq)

  # Getting the maximum length of sequence for padding purpose
  max_seq_length = max(len(x) for x in input_seq)
  #print(max_seq_length)

  # Padding the sequences and converting them to array
  input_seq = np.array(pad_sequences(input_seq, maxlen=max_seq_length, padding='pre'))
  #print(input_seq)

  # Taking xs and labels to train the model.

  xs = input_seq[:, :-1]        
  labels = input_seq[:, -1]     

  # from tensorflow.keras.utils import to_categorical
  ys = to_categorical(labels, num_classes=vocab_size)


  model = load_model(hd5_file)
  def predict_words(seed, no_words):
    for i in range(no_words):
      token_list = tokenizer.texts_to_sequences([seed])[0]
      token_list = pad_sequences([token_list], maxlen=max_seq_length-1, padding='pre')
      predicted = np.argmax(model.predict(token_list), axis=1)

      new_word = ''

      for word, index in tokenizer.word_index.items():
        if predicted == index:
          new_word = word
          break
      seed += " " + new_word
    #print(seed)
    return (seed)

  seed_text = txt
  next_words = 5
  x = predict_words(seed_text, next_words)
  return (x)


def sentiment_analysis(inp_text):
  def remove_special_char(text):
      #replace special characters with ''
      text = re.sub('[^\w\s]', '', text)
      #remove chinese character
      text = re.sub(r'[^\x00-\x7f]',r'', text)
      #remove numbers
      text = re.sub('\d+', '', text)
      text = re.sub('_', '', text)
      text = re.sub('\s+', ' ', text)
      text = text.strip()
      text = unicodedata.normalize('NFKD', text).encode('ascii', 'ignore').decode('utf-8', 'ignore')

generate/templates/generate/final.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

      <style>
        input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }
  body{
    width: 70%;
    height: 30%;
    background-image: url('https://i.postimg.cc/90899537/text.jpg');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  
    
  }
  
  input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }
  
  input[type=submit]:hover {
    background-color: #45a049;
  }
  
  div {
    
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 60px;
    margin-left: 40%;
    margin-top: 20%;
    opacity: 90%;
  }
  p {
            text-shadow: 2px 2px 5px red;
            font-size: 27px;
            text-align: center;
            }
      </style>
  </head>
  

</head>
<body>
 
  <div>
    <p>Final message for sentimental analysis </p>
    
  <!-- </form> -->
  <form action="{% url 'generate:sentimental' %}"    id="veryfyotp" method="post">
    {% csrf_token %}

    <label for="fname">My Message: </label>
    <textarea name="final_senti" rows="5" cols="70" value="{{ msg4 }}">{{ msg }}</textarea>

    <input type="submit" value="Go for Sentimental!!">
  </form>
</div>

<br>

</body>
</html>

generate/templates/generate/gen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body{
  
    background-image: url('https://i.postimg.cc/90899537/text.jpg');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  
    
  }

      /* https://i.postimg.cc/90899537/text.jpg */
      h1 {
            text-shadow: 2px 2px 5px red;
            font-size: 40px;
            }
    </style>
      <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" />

</head>

<body style="padding-top: 3%;">
  <center><h1 style="padding-bottom: 3%;">Text generation messages</h1></center>
<!-- 
  <form action="{% url 'generate:final' %}"  method="post">
    {% csrf_token %}
    
    <br> Message 1: 
    <textarea name="final_msg" rows="5" cols="50" value="{{ msg1 }}">{{ msg1 }}</textarea><br>

    <input type="submit" value="I like this one">
  </form>
  <form action="{% url 'generate:final' %}"  method="post">
    {% csrf_token %}

    <br> Message 2:
    <textarea name="final_msg" rows="5" cols="50" value="{{ msg2 }}">{{ msg2 }}</textarea>

    <input type="submit" value="I like this one">
  </form>
  <form action="{% url 'generate:final' %}"  method="post">
    {% csrf_token %}

    <br> Message 3:
    <textarea name="final_msg" rows="5" cols="50" value="{{ msg3 }}">{{ msg3 }}</textarea>

    <input type="submit" value="I like this one">
  </form>
  <form action="{% url 'generate:record_1' %}"  method="post">
    {% csrf_token %}

    <br> Message:
    <textarea name="message" rows="5" cols="50" value="{{ msg4 }}">{{ msg4 }}</textarea>

    <input type="submit" value="Speak again!!">
  </form>


<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br> -->

<div class="row col-12" style="opacity: 90%;">
  <div class="card col-5" style="margin-left: 50px;">
    <!-- <img class="card-img-top" src="https://images.pexels.com/photos/20787/pexels-photo.jpg?cs=srgb&dl=adorable-animal-cat-20787.jpg&fm=jpg" alt="Card image cap"> -->
    <div class="card-body">
      <h5 class="card-title">Message 1: </h5>
      <form action="{% url 'generate:final' %}"  method="post">
        {% csrf_token %}
        
        <br> 
        <textarea name="final_msg" rows="5" cols="70" value="{{ msg1 }}" readonly>{{ msg1 }}</textarea><br>
        
        <input type="submit" value="I like this one" class="btn btn-primary" style="margin-left: 80%;">
      </form>
    
    </div>
  </div>

  <div class="card col-5" style="margin-left: 150px;">
    <!-- <img class="card-img-top" src="https://images.pexels.com/photos/20787/pexels-photo.jpg?cs=srgb&dl=adorable-animal-cat-20787.jpg&fm=jpg" alt="Card image cap"> -->
    <div class="card-body">
      <h5 class="card-title">Message 2:</h5>
      <form action="{% url 'generate:final' %}"  method="post">
        {% csrf_token %}
    
        <br> 
        <textarea name="final_msg" rows="5" cols="70" value="{{ msg2 }}" readonly>{{ msg2 }}</textarea>
        <br>
        <input type="submit" value="I like this one" class="btn btn-primary" style="margin-left: 80%;">
      </form>
        </div>
  </div>
</div>
<br><br>
<div class="row col-12" style="opacity: 90%;">
  <div class="card col-5" style="margin-left: 50px;">
    <!-- <img class="card-img-top" src="https://images.pexels.com/photos/20787/pexels-photo.jpg?cs=srgb&dl=adorable-animal-cat-20787.jpg&fm=jpg" alt="Card image cap"> -->
    <div class="card-body">
      <h5 class="card-title"> Message 3:</h5>
      <form action="{% url 'generate:final' %}"  method="post">
        {% csrf_token %}
    
        <br>
        <textarea name="final_msg" rows="5" cols="70" value="{{ msg3 }}" readonly>{{ msg3 }}</textarea>
        <br>
        <input type="submit" value="I like this one" class="btn btn-primary" style="margin-left: 80%;">
      </form>
        </div>
  </div>

  <div class="card col-5" style="margin-left: 150px;">
    <!-- <img class="card-img-top" src="https://images.pexels.com/photos/20787/pexels-photo.jpg?cs=srgb&dl=adorable-animal-cat-20787.jpg&fm=jpg" alt="Card image cap"> -->
    <div class="card-body">
      <h5 class="card-title">Message:</h5>
      <form action="{% url 'generate:record_1' %}"  method="post">
        {% csrf_token %}
    
        <br> 
        <textarea name="message" rows="5" cols="70" value="{{ msg4 }}" readonly>{{ msg4 }}</textarea>
        <br>
        <input type="submit" value="Speak again!!" class="btn btn-primary" style="margin-left: 80%;">
      </form>
      <form action="{% url 'generate:final' %}"  method="post">
        {% csrf_token %}
    
        <!-- <br> -->
        <input type="hidden" name="final_msg" rows="5" cols="50" value="{{ msg4 }}" ></input>
        <!-- <br> -->
        <input type="submit" value="I like this one" class="btn btn-primary" style="margin-left: 35%; margin-top: -65px;" >
      </form>
    
        </div>
  </div>
</div>


</body>
</html>

generate/templates/generate/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        body {
                background-image: url('https://s.wsj.net/public/resources/images/BN-DG015_SPEAKI_GR_20140613141802.jpg');
                background-repeat: no-repeat;
                background-attachment: fixed;
                background-size: cover;

        }
        h1 {
            text-shadow: 2px 2px 5px red;
            font-size: 40px;
            }
    </style>
    <title>Title</title>
</head>
<!-- <img src="https://s.wsj.net/public/resources/images/BN-DG015_SPEAKI_GR_20140613141802.jpg" alt="abc"> -->
<body>
    
<center style="padding-top: 5%;">
    <h1 style="color: cornsilk;">Tap on the mic to start recording</h1>
    <br><br><br><br><br><br><br><br><br><br><br><br>
    <a href="{% url 'generate:record' %}">
    <img src="https://i.postimg.cc/hPK4Q8Bs/Capture.jpg" height="200px" width="200px">
    </a>
    
</center>
</body>
</html>

generate/templates/generate/home_1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<button>Tap on the mic to start recording 1111</button>
<a href="{% url 'generate:record_1' %}">
<img src="https://d2dfnis7z3ac76.cloudfront.net/shure_product_db/product_main_images/files/d14/186/8a-/header_transparent/1b16a0366ec3308f6a9fe98908a2216d.png" height="200px" width="200px">
</a>
</body>
</html>

generate/templates/generate/record.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
      input[type=text], select {
  width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
body{
  width: 70%;
  height: 30%;
  background-image: url('https://www.betranslated.com/wp-content/uploads/2019/09/machine-translation-google.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover;

  
}

input[type=submit] {
  width: 100%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}

input[type=submit]:hover {
  background-color: #45a049;
}

div {
  
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 60px;
  margin-left: 40%;
  margin-top: 20%;
  opacity: 90%;
}
    </style>
</head>
<body>
<!-- <form action="{% url 'generate:translate' %}" id="veryfyotp" method="post">
    {% csrf_token %}
    <br> Message: 
    <input name="message" id="msg" value="{{ msg }}"><br>aaasas
    <br> Language:
    <input name="language" id="lang" value="{{ lang }}"><br>

    <input type="submit">

  </form>

<br> -->
<!-- <h3></h3> -->

<div>
  <form action="{% url 'generate:translate' %}" id="veryfyotp" method="post">
    {% csrf_token %}
    <label for="fname">My Message: </label>
    <input type="text" id="msg" name="message" value="{{ msg }}" readonly>

    <label for="lname">Language Spoken:</label>
    <input type="text" id="lang" name="language" value="{{ lang }}">
  
    <input type="submit" value="Submit">
  </form>
</div>
</body>
</html>

generate/templates/generate/record_1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<button>Tap on the mic to start recording</button>
<a href="{% url 'generate:record_1' %}">
<img src="https://d2dfnis7z3ac76.cloudfront.net/shure_product_db/product_main_images/files/d14/186/8a-/header_transparent/1b16a0366ec3308f6a9fe98908a2216d.png" height="200px" width="200px">
</a>
</body>
</html>

generate/templates/generate/sentimental.html
<!DOCTYPE html>
<html lang="en">
<head>
  <head>
    <meta charset="UTF-8">
    <title>Title</title>

      <style>
        input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }
  body{
    width: 70%;
    height: 30%;
    background-image: url('https://expertsystem.com/wp-content/uploads/2019/06/Sentiment-analysis-e1566481971615.jpg');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  
    
  }
  
  input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }
  
  input[type=submit]:hover {
    background-color: #45a049;
  }
  
  #id1 {
    
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 60px;
    margin-left: 10%;
    margin-top: 20%;
    opacity: 90%;
    width: 700px;
    height: 400px;
  }
  p {
            text-shadow: 2px 2px 5px red;
            font-size: 27px;
            text-align: center;
            }
      </style>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <style>
      * {
        box-sizing: border-box;
      }
      
      /* Create two equal columns that floats next to each other */
      .column {
        float: right;
        width: 20%;
        padding: 10px;
        /*margin-bottom: 20%; */
        height: 300px; /* Should be removed. Only for demonstration */
      }
      
      /* Clear floats after the columns */
      .row:after {
        content: "";
        display: table;
        clear: both;
      }
      </style>
  </head>
<body>
  <div class="row">
      <div id="id1">
        <p> Sentimental page</p>
      </form>
      <form action="" method="post">
        {% csrf_token %}

        <label for="lname">Message :</label>
        <textarea name="message" rows="5" cols="70" value="{{ msg }}">{{ msg }}</textarea>
        <br>
        <label for="lname">Status :</label><br>
        {% if  status  == "positive" %}
          <input style="width: 520px;height: 30px;color:green;" name="status" id="stat"  value="{{ status }}"><br>
        {% elif status == "negative" %}    
          <input style="width: 520px;height: 30px;color: red" name="status" id="stat"  value="{{ status }}"><br>
        {% else %}
          <input style="width: 520px;height: 30px;color: orange" name="status" id="stat"  value="{{ status }}"><br>
        {% endif %}    


        <p> Reached final state..</p>
        <!-- <input type="submit" value="reached final state"> -->
      </form>
    </div>
    <div class="column" style="margin-top: -35%;">
    {% if  status  == "positive" %}
      <img src= "https://images-na.ssl-images-amazon.com/images/I/71ZtQnzOU4L._SL1500_.jpg" style="width: 300px;opacity: 90%;background-color: #f2f2f2;">
    {% elif status == "negative" %}
      <img src="https://i.pinimg.com/564x/b0/41/75/b04175fd1ffbefdc02d90136c262a6e3.jpg" style="width: 300px;opacity: 90%;background-color: #f2f2f2;">
    {% else %}
      <img src="https://i.pinimg.com/originals/51/20/1e/51201ec176416783700f8369dcbe5245.png" style="width: 300px;opacity: 90%;background-color: #f2f2f2;">
    {% endif %}
    </div>
  </div>
<br>

</body>
</html>

generate/templates/generate/trans.html
<!DOCTYPE html>
<html lang="en">

    <head>
      <meta charset="UTF-8">
      <title>Title</title>
      <style>
        input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }
  body{
    width: 70%;
    height: 30%;
    background-image: url('https://www.betranslated.com/wp-content/uploads/2019/09/machine-translation-google.jpg');
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-size: cover;
  
    
  }
  
  input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }
  
  input[type=submit]:hover {
    background-color: #45a049;
  }
  
  div {
    
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 60px;
    margin-left: 40%;
    margin-top: 20%;
    opacity: 90%;
  }
  p {
            text-shadow: 2px 2px 5px red;
            font-size: 27px;
            text-align: center;
            }
      </style>
  </head>
  

<body>
<!-- Text you have spoken translated into english 

<form action="{% url 'generate:text_gen' %}" id="veryfyotp" method="post">
    {% csrf_token %}
    <br> Message: 
    <input name="message" id="msg" value="{{ msg }}"><br>
    <br> Which language you needed to translate? :
    <input name="language" id="lang" value=""><br>


    <input type="submit">

  </form>


<br> -->


<div>
  <p>Text you have spoken translated into english </p>
  
  <form action="{% url 'generate:text_gen' %}" id="veryfyotp" method="post">
    {% csrf_token %}
    <label for="fname">My Message: </label>
    <input type="text" id="msg" name="message" value="{{ msg }}" readonly>

    <label for="lname">Which language you needed to translate? :</label>
    <input type="text" id="lang" name="language" value="">
  
    <input type="submit" value="Submit">
  </form>
</div>

<!-- <a href="{% url 'generate:text_gen' %}">Next step for text generation </a> -->
</body>
</html>